FROM python:3.10.0-bullseye

RUN pip install dash dash_bootstrap_components dash_admin_components pandas scikit-learn pyparsing statsmodels dash_bio python-dotenv
RUN mkdir /data

COPY /dash_220426 /data/dash
WORKDIR /data/dash
EXPOSE 8066
ENTRYPOINT ["python","index.py"]

